### ISSUE TITLE
Bug in exported app

### ISSUE THREAD

**Issue by grumpycoder100** [Grumpy-Games-Studios/Planets_the_beginning_beta#2]
There's a bug when users are prompted to press the back button to exit the game, but then on some devices, pressing the back button doesn't exit the game.

**Comment by grumpyspaceman100** [comment]
What devices specifically?

**Comment by grumpycoder100** [comment]
Lumia 635, Lumia 920 and Lumia 1020 and Lumia Icon.

**Comment by grumpyspaceman100** [comment]
I'm on it.

**Comment by grumpyspaceman100** [comment]
bbefa9b

**Comment by grumpyspaceman100** [comment]
Fixed in latest commit bbefa9b
