### ISSUE TITLE
App doesn't close when users press the back button

### ISSUE THREAD

**Issue by grumpyspaceman100** [Grumpy-Games-Studios/Planets_the_beginning_beta#6]
Noticed this issue happens on these few models:
-Lumia 920(Windows 10 Mobile Insider Preview Build 10586.63)
-Lumia 950(Windows 10 Mobile Insider Preview Build 10586.63)
-Lumia Icon(Windows Phone 8.1 Lumia Denim)
-Lumia 830(Windows 10 Mobile Build 10586.39)
-Lumia 520(Windows Phone 8.1 Lumia Denim)

**Comment by grumpycoder100** [comment]
Are these the only phone models that are having this issue?

**Comment by grumpyspaceman100** [comment]
@grumpycoder100 yes, these are the only ones.

**Comment by grumpycoder100** [comment]
Alright, then we'll wait for @grumpybee100 to fix it then.

**Comment by grumpybee100** [comment]
Guys I will be checking in a new re edited file through visual studio online later, so check that out.
